import sys
import os
import re
import importlib
import glob
from ftplib import FTP
import telnetlib
import socket

# Try importing paramiko for SSH, handle if missing gracefully
try:
    import paramiko
    HAS_PARAMIKO = True
except ImportError:
    HAS_PARAMIKO = False

def parse_mac_file(filepath):
    """
    Parses the MAC_FILE generated by Option 3 (Interrogate)
    Returns a dictionary of discovered services, ports, and metadata.
    """
    data = {
        "ip": None,
        "vendor": None,
        "model": None,
        "firmware": None,
        "open_ports": {},  # port: service_name
        "onvif_unauth": False,
        "rtsp_url": None
    }

    if not os.path.exists(filepath):
        return data

    with open(filepath, 'r') as f:
        content = f.read()

    # Extract IP and Vendor from header
    ip_match = re.search(r'IP:\s+([0-9\.]+)', content)
    if ip_match: data["ip"] = ip_match.group(1)

    vendor_match = re.search(r'Vendor:\s+(.+)', content)
    if vendor_match: data["vendor"] = vendor_match.group(1).strip()

    # Extract ONVIF info
    if "Connection: Port " in content and "(Unauthenticated)" in content:
        data["onvif_unauth"] = True

    model_match = re.search(r'Model:\s+(.+)', content)
    if model_match: data["model"] = model_match.group(1).strip()

    fw_match = re.search(r'FirmwareVersion:\s+(.+)', content)
    if fw_match: data["firmware"] = fw_match.group(1).strip()

    rtsp_match = re.search(r'SUCCESS_URL:(.+)', content)
    if rtsp_match: data["rtsp_url"] = rtsp_match.group(1).strip()

    # Parse Nmap port section
    # Example line: "80/tcp  open  http    lighttpd 1.4.53"
    port_lines = re.findall(r'^(\d+)/(tcp|udp)\s+open\s+([^\s]+)', content, re.MULTILINE)
    for port, proto, service in port_lines:
        data["open_ports"][int(port)] = service

    return data

def load_credentials(creds_file):
    """Loads username:password tuples from the credentials file."""
    creds = []
    if os.path.exists(creds_file):
        with open(creds_file, 'r') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#'):
                    parts = line.split(':', 1)
                    if len(parts) == 2:
                        creds.append((parts[0], parts[1]))
    return creds

def test_ftp_auth(ip, port, creds):
    """Tests FTP for anonymous or default credentials."""
    results = []
    # Test Anonymous first
    try:
        ftp = FTP()
        ftp.connect(ip, port, timeout=3)
        ftp.login() # Default is anonymous
        results.append(f"CRITICAL: FTP access allowed anonymously (Port {port})")
        ftp.quit()
        return results
    except Exception:
        pass

    # Test default creds
    for user, pwd in creds:
        try:
            ftp = FTP()
            ftp.connect(ip, port, timeout=3)
            ftp.login(user=user, passwd=pwd)
            results.append(f"CRITICAL: FTP default credentials found ({user}:{pwd}) on Port {port}")
            ftp.quit()
            return results
        except Exception:
            pass

    return results

def test_ssh_auth(ip, port, creds):
    """Tests SSH for default credentials if paramiko is installed."""
    results = []
    if not HAS_PARAMIKO:
        results.append(f"INFO: SSH port {port} is open, but paramiko library is missing. Cannot test credentials.")
        return results

    client = paramiko.SSHClient()
    client.set_missing_host_key_policy(paramiko.AutoAddPolicy())

    for user, pwd in creds:
        try:
            client.connect(ip, port=port, username=user, password=pwd, timeout=3, allow_agent=False, look_for_keys=False)
            results.append(f"CRITICAL: SSH default credentials found ({user}:{pwd}) on Port {port}")
            client.close()
            return results
        except Exception:
            pass

    return results

def test_telnet_auth(ip, port, creds):
    """Tests Telnet for default credentials."""
    results = []

    for user, pwd in creds:
        try:
            tn = telnetlib.Telnet(ip, port, timeout=3)
            # Basic attempt to wait for login prompts and send creds
            tn.read_until(b"login: ", timeout=2)
            tn.write(user.encode('ascii') + b"\n")

            if pwd:
                tn.read_until(b"Password: ", timeout=2)
                tn.write(pwd.encode('ascii') + b"\n")

            # Wait a moment to see if we get a shell prompt or an error
            out = tn.read_until(b"#", timeout=2).decode('ascii')

            # Extremely basic check: if we see a standard shell prompt, we likely succeeded
            if "#" in out or "$" in out or ">" in out:
                results.append(f"CRITICAL: Telnet default credentials found ({user}:{pwd}) on Port {port}")
                tn.close()
                return results

            tn.close()
        except Exception:
            pass

    return results

def evaluate_baseline_security(target_data, creds):
    """
    Evaluates basic security hygiene: plaintext protocols, open management ports,
    and attempts basic credential brute-forcing on known services.
    """
    findings = []
    ip = target_data["ip"]
    open_ports = target_data["open_ports"]

    if not ip or not open_ports:
        findings.append("ERROR: No IP or port data found in MAC_FILE. Did nmap complete?")
        return findings

    # Check for plaintext / insecure protocols
    insecure_services = {
        21: ("FTP", "Transmits files and credentials in plaintext."),
        23: ("Telnet", "Transmits all data, including management credentials, in plaintext."),
        80: ("HTTP", "Unencrypted web management interface. Vulnerable to interception.")
    }

    for port, service in open_ports.items():
        if port in insecure_services:
            name, desc = insecure_services[port]
            findings.append(f"WARNING: Insecure Protocol {name} (Port {port}) is OPEN. {desc}")

            # Actively test credentials against FTP and Telnet
            if port == 21:
                findings.extend(test_ftp_auth(ip, port, creds))
            elif port == 23:
                findings.extend(test_telnet_auth(ip, port, creds))

        elif port == 22 or service == 'ssh':
            findings.extend(test_ssh_auth(ip, port, creds))

    # Check ONVIF
    if target_data.get("onvif_unauth"):
        findings.append("CRITICAL: ONVIF API is accessible without authentication. Device configurations can be altered.")

    if not findings:
        findings.append("INFO: Baseline port security looks clean (No obvious insecure defaults found).")

    return findings

def run_plugins(target_data):
    """
    Dynamically loads and executes any python scripts in the security_plugins/ folder.
    Each plugin must define a `run(target_data)` function returning a list of strings (findings).
    """
    plugin_findings = []
    plugin_dir = "security_plugins"
    if not os.path.exists(plugin_dir):
        return plugin_findings

    sys.path.insert(0, os.path.abspath("."))

    for file in glob.glob(f"{plugin_dir}/*.py"):
        basename = os.path.basename(file)
        if basename == "__init__.py" or not basename.endswith(".py"):
            continue

        module_name = f"{plugin_dir}.{basename[:-3]}"
        try:
            mod = importlib.import_module(module_name)
            if hasattr(mod, "run"):
                plugin_findings.append(f"\n--- Plugin: {basename} ---")
                results = mod.run(target_data)
                if results:
                    plugin_findings.extend(results)
                else:
                    plugin_findings.append("Status: Clean / No vulnerabilities found.")
        except Exception as e:
            plugin_findings.append(f"ERROR: Failed to run plugin {basename}: {e}")

    return plugin_findings

def main():
    if len(sys.argv) < 4:
        print("Usage: python security_evaluator.py <IP> <MAC_FILE_PATH> <CREDS_FILE>")
        sys.exit(1)

    ip = sys.argv[1]
    mac_file = sys.argv[2]
    creds_file = sys.argv[3]

    print(f"Evaluating security for {ip} based on {mac_file}...")

    target_data = parse_mac_file(mac_file)
    creds = load_credentials(creds_file)

    report = []
    report.append("\n" + "="*40)
    report.append("       SECURITY EVALUATION REPORT")
    report.append("="*40)
    report.append(f"Target IP: {target_data['ip']}")
    report.append(f"Device: {target_data['vendor']} {target_data['model']}")
    report.append(f"Firmware: {target_data['firmware']}")
    report.append("-" * 40)

    # 1. Baseline Assessment
    report.append("\n[ BASELINE ASSESSMENT ]")
    baseline = evaluate_baseline_security(target_data, creds)
    for finding in baseline:
        report.append(f"  {finding}")

    # 2. Extensible Plugins
    report.append("\n[ PLUGIN ASSESSMENT ]")
    plugins = run_plugins(target_data)
    if plugins:
        for finding in plugins:
            report.append(f"  {finding}")
    else:
        report.append("  No active plugins found in security_plugins/")

    report.append("=" * 40 + "\n")

    report_text = "\n".join(report)

    # Output to stdout so it can be appended to MAC_FILE by bash
    print(report_text)

if __name__ == "__main__":
    main()
